### model
model_name_or_path: ./Qwen2.5-VL-7B-Instruct
adapter_name_or_path: ./saves/qwen-7b_SAHZU_train_17200/lora/sft
image_max_pixels: 262144
video_max_pixels: 16384


### method
stage: sft
do_predict: true
finetuning_type: lora


### dataset
eval_dataset: Qwen_FAHZC
template: qwen2_vl
cutoff_len: 3072
max_samples: 269
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen_FAHZC
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
ddp_timeout: 180000000